const en = {
  aiPlanTitle: "Your AI improvement plan",
  aiPlanFallbackSummary: "Review these suggestions before applying them. The local ATS score remains the reference.",
  potentialScore: "Potential score",
  potentialScoreHint: "up to, if identified issues are fixed",
  priorityTitle: "Priority action plan",
  priorityHigh: "High priority",
  priorityMedium: "Medium priority",
  priorityLow: "Low priority",
  keywordTriageTitle: "Review suggested keywords",
  keywordTriageHint: "Confirm only skills and terms that truthfully describe your experience.",
  keywordRelevant: "Relevant",
  keywordHave: "I have this skill",
  keywordIgnore: "Not relevant",
  applyConfirmedKeywords: "Add confirmed skills to resume text",
  keywordsApplied: "Confirmed skills were added. Review their placement before exporting.",
  rewriteTitle: "Review bullet rewrites",
  rewriteHint: "Edit each suggestion, then accept it individually. No change is automatic.",
  currentVersion: "Current version",
  suggestedVersion: "Suggested version",
  acceptRewrite: "Accept rewrite",
  ignoreRewrite: "Ignore",
  applied: "Applied",
  ignored: "Ignored",
  originalNotFound: "The original text changed, so this rewrite was not applied.",
  phrasesTitle: "Phrases worth considering",
  recheckAfterChanges: "Re-check after changes",
  continueInBuilder: "Continue in Resume Builder",
};

const fr = {
  aiPlanTitle: "Votre plan d’amélioration par IA",
  aiPlanFallbackSummary: "Vérifiez chaque suggestion avant de l’appliquer. Le score ATS local reste la référence.",
  potentialScore: "Score potentiel",
  potentialScoreHint: "au maximum, si les problèmes détectés sont corrigés",
  priorityTitle: "Plan d’action prioritaire",
  priorityHigh: "Priorité élevée",
  priorityMedium: "Priorité moyenne",
  priorityLow: "Priorité faible",
  keywordTriageTitle: "Vérifiez les mots-clés suggérés",
  keywordTriageHint: "Confirmez uniquement les compétences et termes qui décrivent réellement votre expérience.",
  keywordRelevant: "Pertinent",
  keywordHave: "Je possède cette compétence",
  keywordIgnore: "Non pertinent",
  applyConfirmedKeywords: "Ajouter les compétences confirmées au CV",
  keywordsApplied: "Les compétences confirmées ont été ajoutées. Vérifiez leur emplacement avant l’export.",
  rewriteTitle: "Vérifiez les reformulations",
  rewriteHint: "Modifiez chaque suggestion puis acceptez-la séparément. Aucun changement n’est automatique.",
  currentVersion: "Version actuelle",
  suggestedVersion: "Version suggérée",
  acceptRewrite: "Accepter la reformulation",
  ignoreRewrite: "Ignorer",
  applied: "Appliquée",
  ignored: "Ignorée",
  originalNotFound: "Le texte original a changé ; cette reformulation n’a pas été appliquée.",
  phrasesTitle: "Formulations à envisager",
  recheckAfterChanges: "Vérifier à nouveau",
  continueInBuilder: "Continuer dans le créateur de CV",
};

const ar = {
  aiPlanTitle: "خطة التحسين بالذكاء الاصطناعي",
  aiPlanFallbackSummary: "راجع كل اقتراح قبل تطبيقه. تبقى نتيجة ATS المحلية هي المرجع.",
  potentialScore: "النتيجة المحتملة",
  potentialScoreHint: "كحد أقصى بعد إصلاح المشكلات المحددة",
  priorityTitle: "خطة العمل حسب الأولوية",
  priorityHigh: "أولوية عالية",
  priorityMedium: "أولوية متوسطة",
  priorityLow: "أولوية منخفضة",
  keywordTriageTitle: "راجع الكلمات المفتاحية المقترحة",
  keywordTriageHint: "أكد فقط المهارات والمصطلحات التي تصف خبرتك الحقيقية.",
  keywordRelevant: "مناسب",
  keywordHave: "أمتلك هذه المهارة",
  keywordIgnore: "غير مناسب",
  applyConfirmedKeywords: "إضافة المهارات المؤكدة إلى نص السيرة",
  keywordsApplied: "تمت إضافة المهارات المؤكدة. راجع موضعها قبل التصدير.",
  rewriteTitle: "راجع إعادة صياغة النقاط",
  rewriteHint: "عدّل كل اقتراح ثم اقبله منفردًا. لا يُطبق أي تغيير تلقائيًا.",
  currentVersion: "الصياغة الحالية",
  suggestedVersion: "الصياغة المقترحة",
  acceptRewrite: "قبول الصياغة",
  ignoreRewrite: "تجاهل",
  applied: "تم التطبيق",
  ignored: "تم التجاهل",
  originalNotFound: "تغيّر النص الأصلي، لذلك لم تُطبق الصياغة.",
  phrasesTitle: "عبارات يمكن أخذها في الاعتبار",
  recheckAfterChanges: "إعادة الفحص",
  continueInBuilder: "المتابعة في منشئ السيرة الذاتية",
};

const copies = { en, fr, ar };
export const getAtsAiCopy = (locale) => copies[locale] || en;
